services:
  - type: web
    name: fermax-propiedades
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_ASSETS_URL
        value: /
      - key: VITE_TEST_ENABLE
        value: "false"
